#!/bin/sh
#
# ScratchMUD autorun script.
#
# \par Copyright
# Copyright (C) 1999-2019 scratchmud.org
# All rights reserved.
#
# \author Geoffrey Davis <gdavis@scratchmud.org>
#

AutorunKillFile=".autorun.kill"
while ( : ) do
  ./bin/scratchd
  if [ -r $AutorunKillFile ]; then
    rm -f $AutorunKillFile
    exit
  fi
  sleep 60
done
